#!/usr/bin/env bash
# This script displays user information from the /etc/passwd file.

passwd_file="/etc/passwd"

while IFS=: read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < "$passwd_file"
