#!/usr/bin/env bash
# This script displays user information from the /etc/passwd file.

passwd_file="/etc/passwd"

while IFS=: read -r username _ uid gid desc home shell _; do
    echo "The user $username is part of the $gid gang, lives in $home, and rides $shell."
    echo "$uid's place is protected by the passcode x, more info about the user here: $desc"
done < "$passwd_file"
