#!/usr/bin/env bash
# This script creates a PID file, displays a message indefinitely, and handles signals

echo $$ > /var/run/myscript.pid

handle_sigterm() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 0
}

handle_sigint() {
    echo "Y U no love me?!"
}

trap 'handle_sigterm' SIGTERM SIGQUIT
trap 'handle_sigint' SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 2
done

