#!/usr/bin/env bash
#use ps to find relevant lines shellcheck disable=SC2009, Get the PID of the parent Bash process
parent_pid=$$
ps_output=$(ps -e -o pid,ppid,args | grep "bash")
echo "PID     PPID    Command"

while read -r line; do
    echo "$line"
done <<< "$ps_output"

