#!/usr/bin/env bash
# This script displays lines containing the "bash" word, allowing you to identify your Bash process PID.
# shellcheck disable=SC2009 (Don't complain about using ps x)
ps x | grep bash | awk '$2 == "'$SHELL'" {print}'

