#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond.sh process using kill, Get the PID of the 4-to_infinity_and_beyond.sh process
pid=$(pgrep -f 4-to_infinity_and_beyond.sh)
if [[ -n "$pid" ]]; then
  kill "$pid"
  echo "Terminated"
else
  echo "Process 4-to_infinity_and_beyond.sh not found."
fi
